# model/tokenizer
device: "cpu"
model_name: "decapoda-research/llama-7b-hf" # add model here
# model_name: "chavinlo/gpt4-x-alpaca" # add model here
tokenizer_name: "gpt2" # add model here
gradient_checkpointing: true
save_name: "nomic-ai/gpt4all-full-multi-turn"

# dataset
streaming: false
num_proc: 16
dataset_path: "datasets/cci/GPT4ALL-cci.jsonl" # update
max_length: 512
batch_size: 4 

# train dynamics
lr: 5.0e-5
eval_every: 800
eval_steps: 100
save_every: 800
output_dir: "ckpts/gpt4all-full-multi"
checkpoint: null
lora: false
warmup_steps: 100
num_epochs: 2

# logging
wandb: false
wandb_entity: "huangch" # update
wandb_project_name: "gpt4alli-cci" # update
seed: 42

