# model/tokenizer
model_name: "decapoda-research/llama-7b-hf" # add model here
tokenizer_name: "gpt2" # add model here
gradient_checkpointing: true
save_name: "huangch/gpt4all-full-multi-cci-turn"

# dataset
streaming: false
num_proc: 32
dataset_path: "configs/deepspeed/training_data/cci.jsonl" # update
max_length: 1024
batch_size: 16

# train dynamics
lr: 5.0e-5
eval_every: 800
eval_steps: 100
save_every: 800
output_dir: "ckpts/gpt4all-full-multi-cci"
checkpoint: null
lora: false
warmup_steps: 100
num_epochs: 2

# logging
wandb:false 
wandb_entity: "huangch" # update
wandb_project_name: "gpt4all" # update
seed: 42

